-- CreateEnum
CREATE TYPE "AGENT_ROLE" AS ENUM ('INBOUND_CHAT', 'POST_CALL_CHAT', 'INBOUND_CALL', 'OUTBOUND_PRE_SALES_CALL', 'OUTBOUND_SALES_CALL', 'FEEDBACK_CALL');

-- AlterTable
ALTER TABLE "agents" ADD COLUMN     "role" "AGENT_ROLE" NOT NULL DEFAULT 'INBOUND_CHAT',
ADD COLUMN     "workflow_id" TEXT;

-- AlterTable
ALTER TABLE "chats" ADD COLUMN     "transfer_reason" TEXT;
